# fly.toml app configuration file generated for starter-template on 2023-11-06T11:19:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "starter-template"
primary_region = "cdg"
kill_timeout = "15s"
swap_size_mb = 512

[build]

[env]
  PRIVATE_BACKEND_URL = "http://localhost:8080"
  PUBLIC_BACKEND_URL = "https://starter-template.fly.dev"
  PUBLIC_SITE_URL = "https://starter-template.fly.dev"

[[mounts]]
  source = "pb_data"
  destination = "/pb_data"

[http_service]
  internal_port = 8070
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "5s"
    timeout = "30s"
    grace_period = "45s"
    method = "GET"
    path = "/health"
